### ISSUE TITLE
Windows 32/64 bit binaries (without bmi2-option) are missing

### ISSUE THREAD

**Issue by yellow-panther** [kyleaforrester/doughboy#1]
Hello kyleaforrester,
can you build such mentioned above binaries and host these Windows files on GitHub, too?

**Comment by kyleaforrester** [comment]
Hi yellow-panther,

I plan to do so when ready.  Unfortunately the project is not complete yet, I am still fleshing out the engine :)

Thank you for your interest and check back in a few weeks!
